nginx-push-stream:
  image: z7zmey/nginx-push-stream
  container_name: nginx-push-stream
  expose:
    - 80
  volumes:
    - ./push-stream.conf:/etc/nginx/nginx.conf

publisher:
  image: gallna/php5:ffmpeg
  expose:
    - 9000
  links:
    - nginx-push-stream
    - ffmpeg-stream
    - vlc-stream
  volumes:
    - ./publisher:/var/www/public
  environment:
    DEBUG: 'true'

subscriber:
  image: gallna/php5:ffmpeg
  expose:
    - 9000
  links:
    - nginx-push-stream
  volumes:
    - ./subscriber:/var/www/public
  environment:
    DEBUG: 'true'

nginx-publisher:
  image: gallna/docker-nginx:php-fpm
  container_name: video-publisher
  expose:
    - 80
  links:
    - publisher:php-fpm
  volumes_from:
    - publisher

nginx-subscriber:
  image: gallna/docker-nginx:php-fpm
  container_name: video-subscriber
  expose:
    - 80
  links:
    - subscriber:php-fpm
  volumes_from:
    - subscriber


ffmpeg-stream:
  image: jrottenberg/ffmpeg
  container_name: ffmpeg-stream
  expose:
    - 80
  command: -i http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4 -listen 1 -f mpeg http://0.0.0.0:80/ElephantsDream.mp4

vlc-stream:
  image: gallna/stream-proxy:vlc
  container_name: vlc-stream
  expose:
    - 8080
  command: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4
